### ISSUE TITLE
Farvetema

### ISSUE THREAD

**Issue by poul5553** [Zainde/The-best-team-ever#10]
Overordnet farvetema til siden 

![image](https://user-images.githubusercontent.com/37714314/43824720-0bc3a0ea-9af3-11e8-9ae0-d575d133638c.png)

**Comment by clausjuul** [comment]
![green colors](https://user-images.githubusercontent.com/42136084/43824941-abb89f1a-9af3-11e8-99db-82a84de4355a.PNG)
