### ISSUE TITLE
Design & Layout

### ISSUE THREAD

**Issue by mftw** [Zainde/The-best-team-ever#11]
Bliv enige om:
Margins
Borders
Shadows
Fonts

Efter valgte farvetema.

**Comment by mftw** [comment]
Jeg foreslår:
- Open Sans
- 15px margins (grid-gap, margin-top/left/right/bottom)
- Ingen border
- Shadows (lille i top, større i bund)
- De flotte farver Claus har fundet.

**Comment by clausjuul** [comment]
https://codepen.io/sdthornton/pen/wBZdXq

**Comment by Zainde** [comment]
.shadow {
  box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
}

**Comment by clausjuul** [comment]
![wireframe-1](https://user-images.githubusercontent.com/42136084/43830871-a03f4b52-9b02-11e8-8165-bbe95288e661.png)

**Comment by mftw** [comment]
Margins ændres til 16px
