### ISSUE TITLE
Medier (Video Billede Lyd)

### ISSUE THREAD

**Issue by mftw** [Zainde/The-best-team-ever#15]
Find relevante medier til et udendørs event site.

**Comment by Zainde** [comment]
her er nogle billeder

![y1130419](https://user-images.githubusercontent.com/42198931/43827301-d4714d8e-9af9-11e8-928a-ed5216a40501.jpg)
![y1120409](https://user-images.githubusercontent.com/42198931/43827309-d775b3ee-9af9-11e8-9ad7-563e3ff0094a.jpg)
![y1130428](https://user-images.githubusercontent.com/42198931/43827096-4d16fd98-9af9-11e8-83f6-dad468c13207.jpg)
![y1140444](https://user-images.githubusercontent.com/42198931/43827149-72628680-9af9-11e8-85c8-2c2c30560f1f.jpg)
![y1140445](https://user-images.githubusercontent.com/42198931/43827150-72834f1e-9af9-11e8-8ea7-673ba5c7a296.jpg)
